#application name
spring.application.name=Hazel-n-Grazel

#server port
server.port=9090

#AWS RDS DB configuration
#spring.datasource.url=jdbc:postgresql://gns-db-instance.cdm604eg66vo.us-west-1.rds.amazonaws.com:5432/gns_db
#spring.datasource.username=postgres
#spring.datasource.password=16z9CgXnFy2274FEP

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name= org.postgresql.Driver

#Supabase DB configuration
#spring.datasource.url=jdbc:postgresql://db.lecbzscvjimhowoznppm.supabase.co:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=${DB_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Swagger configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha

#file configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=500MB
spring.servlet.multipart.file-size-threshold=10KB
